---

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - script: env
    displayName: 'Debug environment'

  - task: AzureCLI@2
    inputs:
      addSpnToEnvironment: true
      azureSubscription: 'azurerm-oidc'
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        # Inherit Azure CLI service connection
        export ARM_CLIENT_ID=$servicePrincipalId
        export ARM_OIDC_TOKEN=$idToken
        export ARM_TENANT_ID=$tenantId
        export ARM_SUBSCRIPTION_ID=$(az account show --query id -o tsv)
        export ARM_USE_OIDC=true
        # terraform init
        # terraform apply -auto-approve
        env
        aaz group list
    displayName: 'Azure CLI'
